// gen_gcode.js
// Synthetic OrcaSlicer-2.4.2-style verbose G-code generator, tuned to Bambu Lab P1S
// defaults (0.4mm nozzle, 1.75mm filament, 0.2mm layer height), for testing the
// KintsugiVase splicer against realistic input shapes without needing a real slice.

const FILAMENT_DIA = 1.75;
const FILAMENT_AREA = Math.PI * Math.pow(FILAMENT_DIA / 2, 2); // mm^2

function eForSegment(lengthMM, widthMM, heightMM) {
    // Rectangular approximation used by slicers for extrusion cross-section.
    const crossSectionArea = widthMM * heightMM;
    return (lengthMM * crossSectionArea) / FILAMENT_AREA;
}

function squareLoopPoints(cx, cy, halfSize) {
    return [
        [cx - halfSize, cy - halfSize],
        [cx + halfSize, cy - halfSize],
        [cx + halfSize, cy + halfSize],
        [cx - halfSize, cy + halfSize],
        [cx - halfSize, cy - halfSize],
    ];
}

// Emits one circular wall loop as 4 quarter-circle G2/G3 arcs — matching what OrcaSlicer's
// "Arc fitting" actually produces for a round perimeter (a handful of arc commands, not a
// straight-line polygon approximation). This is the exact code path that was silently
// invisible to the splicer/preview before the [01]->[0-3] fix.
function circularWallArcLines(cx, cy, radius, wallWidth, layerHeight, feed) {
    const lines = [];
    const quarterLen = (Math.PI / 2) * radius;
    const e = eForSegment(quarterLen, wallWidth, layerHeight);
    const pts = [
        [cx + radius, cy], [cx, cy + radius], [cx - radius, cy], [cx, cy - radius], [cx + radius, cy],
    ];
    lines.push(`G1 X${pts[0][0].toFixed(3)} Y${pts[0][1].toFixed(3)} F6000 ; travel to arc wall start`);
    for (let i = 1; i < pts.length; i++) {
        const [sx, sy] = pts[i - 1];
        const [ex, ey] = pts[i];
        const iOff = cx - sx, jOff = cy - sy; // center offset relative to arc start, per G2/G3 spec
        lines.push(`G3 X${ex.toFixed(3)} Y${ey.toFixed(3)} I${iOff.toFixed(3)} J${jOff.toFixed(3)} E${e.toFixed(5)} F${feed} ; arc-fitted wall segment`);
    }
    return lines;
}

// --- Standard "base" print: multi-wall + grid infill, P1S profile defaults ---
// arcFitWalls: true emits round walls as G2/G3 (matches OrcaSlicer's "Arc fitting" option);
// false (default) keeps the original square G1 polygon for backward-compatible tests.
function generateBaseGcode({ layers = 10, layerHeight = 0.2, wallWidth = 0.45, walls = 2, size = 20, arcFitWalls = false } = {}) {
    const lines = [];
    lines.push('; generated by gen_gcode.js (synthetic, OrcaSlicer 2.4.2 verbose style)');
    lines.push('; total estimated time: 0h 42m 10s');
    lines.push(`; max_z_height: ${(layers * layerHeight).toFixed(2)}`);
    lines.push('M104 S220 ; set hotend temp');
    lines.push('M109 S220 ; wait for hotend temp');
    lines.push('M106 S0 ; fan off first layers');
    lines.push('M83 ; relative extrusion');
    lines.push('G92 E0');

    let f = 1800;
    for (let l = 1; l <= layers; l++) {
        const z = +(l * layerHeight).toFixed(3);
        lines.push(`;LAYER_CHANGE`);
        lines.push(`;Z:${z.toFixed(2)}`);
        lines.push(`;HEIGHT:${layerHeight.toFixed(2)}`);
        lines.push(`G1 Z${z.toFixed(3)} F${f}`);
        if (l === 3) { lines.push('M106 S255 ; fan to full after layer 3'); }

        // Multiple concentric walls (perimeters), largest first — typical outer-in order.
        for (let w = 0; w < walls; w++) {
            const half = (size / 2) - w * wallWidth;
            if (arcFitWalls) {
                lines.push(...circularWallArcLines(0, 0, half, wallWidth, layerHeight, 1800));
                continue;
            }
            const pts = squareLoopPoints(0, 0, half);
            lines.push(`G1 X${pts[0][0].toFixed(3)} Y${pts[0][1].toFixed(3)} F6000 ; travel to wall ${w} start`);
            for (let i = 1; i < pts.length; i++) {
                const [x1, y1] = pts[i - 1];
                const [x2, y2] = pts[i];
                const len = Math.hypot(x2 - x1, y2 - y1);
                const e = eForSegment(len, wallWidth, layerHeight);
                lines.push(`G1 X${x2.toFixed(3)} Y${y2.toFixed(3)} E${e.toFixed(5)} F1800`);
            }
        }

        // Grid infill (a handful of crossing lines) inside the innermost wall.
        const innerHalf = (size / 2) - walls * wallWidth;
        if (innerHalf > 1) {
            const step = 2.5;
            for (let x = -innerHalf; x <= innerHalf; x += step) {
                const y1 = -innerHalf, y2 = innerHalf;
                const len = Math.abs(y2 - y1);
                const e = eForSegment(len, wallWidth, layerHeight);
                lines.push(`G1 X${x.toFixed(3)} Y${y1.toFixed(3)} F6000 ; travel to infill line`);
                lines.push(`G1 X${x.toFixed(3)} Y${y2.toFixed(3)} E${e.toFixed(5)} F3600`);
            }
        }
    }
    lines.push('; end of base print');
    return lines.join('\n');
}

// Emits one layer's spiral wall as a handful of HELICAL G2/G3 arcs (X/Y/Z/E all changing
// within the same arc command) — this is what OrcaSlicer's "Arc fitting" produces when
// applied to spiral-vase mode: since the whole layer is one continuous wall, arc fitting
// can collapse large stretches of it (not just the discrete per-layer walls a normal print
// has) into a handful of long helical arcs, carrying the continuous Z ramp on the arc line
// itself rather than via separate G1 Z moves.
function helicalArcLines(cx, cy, radius, zStart, zEnd, wallWidth, layerHeight, feed, arcsPerLayer) {
    const lines = [];
    const totalLen = 2 * Math.PI * radius;
    const arcLen = totalLen / arcsPerLayer;
    const e = eForSegment(arcLen, wallWidth, layerHeight);
    let prevAngle = 0;
    let prevZ = zStart;
    const pts = [];
    for (let i = 0; i <= arcsPerLayer; i++) {
        const theta = (i / arcsPerLayer) * 2 * Math.PI;
        pts.push([cx + radius * Math.cos(theta), cy + radius * Math.sin(theta), zStart + (zEnd - zStart) * (i / arcsPerLayer)]);
    }
    lines.push(`G1 X${pts[0][0].toFixed(3)} Y${pts[0][1].toFixed(3)} Z${pts[0][2].toFixed(4)} F${feed} ; travel to helical arc start`);
    for (let i = 1; i < pts.length; i++) {
        const [sx, sy] = pts[i - 1];
        const [ex, ey, ez] = pts[i];
        const iOff = cx - sx, jOff = cy - sy;
        lines.push(`G3 X${ex.toFixed(3)} Y${ey.toFixed(3)} Z${ez.toFixed(4)} I${iOff.toFixed(3)} J${jOff.toFixed(3)} E${e.toFixed(5)} F${feed} ; helical arc-fitted spiral segment`);
    }
    return lines;
}

// --- Spiral vase print: single wall, continuous Z ramp per segment, no infill ---
// layerStartZLift: true emits a standalone `G1 Z{target}` line at the start of each layer
// (before any XY/E content) — common in real slicer output — to reproduce the resume-point
// bug where a line specifying only Z (no X/Y) exposed a fresh-scan-from-origin defect.
// arcFitSpiral: true replaces the per-segment G1 spiral with helicalArcLines() above, to
// reproduce the "entire model renders as solid base-color, chopped/gappy" bug seen when
// Arc fitting is combined with spiral vase mode.
function generateVaseGcode({ layers = 40, layerHeight = 0.2, wallWidth = 0.42, size = 20, segmentsPerLayer = 24, layerStartZLift = false, arcFitSpiral = false, arcsPerLayer = 6 } = {}) {
    const lines = [];
    lines.push('; generated by gen_gcode.js (synthetic, OrcaSlicer 2.4.2 verbose style, spiral_mode)');
    lines.push('; total estimated time: 1h 05m 00s');
    lines.push(`; max_z_height: ${(layers * layerHeight).toFixed(2)}`);
    lines.push('M104 S215 ; vase hotend temp (slightly cooler)');
    lines.push('M109 S215 ; wait for hotend temp');
    lines.push('M106 S200 ; vase fan');
    lines.push('M83 ; relative extrusion');
    lines.push('G92 E0');

    const half = size / 2;
    let prevZ = 0;
    for (let l = 1; l <= layers; l++) {
        const zTarget = +(l * layerHeight).toFixed(4);
        lines.push(`;LAYER_CHANGE`);
        lines.push(`;Z:${zTarget.toFixed(2)}`);
        lines.push(`;HEIGHT:${layerHeight.toFixed(2)}`);
        if (layerStartZLift) {
            lines.push(`G1 Z${zTarget.toFixed(4)} F1200 ; layer-start Z lift (X/Y omitted, unchanged)`);
        }

        if (arcFitSpiral) {
            lines.push(...helicalArcLines(0, 0, half, prevZ, zTarget, wallWidth, layerHeight, 1800, arcsPerLayer));
        } else {
            let lastX = half, lastY = 0;
            // Continuous per-segment Z ramp — this is what real spiral_mode output looks like:
            // Z increases fractionally on almost every line, not just at layer boundaries.
            for (let s = 1; s <= segmentsPerLayer; s++) {
                const theta = (s / segmentsPerLayer) * 2 * Math.PI;
                const x = half * Math.cos(theta);
                const y = half * Math.sin(theta);
                const zFrac = prevZ + (zTarget - prevZ) * (s / segmentsPerLayer);
                const len = Math.hypot(x - lastX, y - lastY);
                const e = eForSegment(len, wallWidth, layerHeight);
                lines.push(`G1 X${x.toFixed(3)} Y${y.toFixed(3)} Z${zFrac.toFixed(4)} E${e.toFixed(5)} F1800`);
                lastX = x; lastY = y;
            }
        }
        prevZ = zTarget;
    }
    lines.push('; end of vase print');
    return lines.join('\n');
}

module.exports = { generateBaseGcode, generateVaseGcode, FILAMENT_AREA };
